version: "3.3"
services:
   api-todo-rs:
    build:
      context: ./app
      dockerfile: Dockerfile
    # pid: host
    networks:
      - default
    expose:
      - "8081"
    ports:
      - "8081:8081"
    container_name: api-todo-rs
    hostname: api-todo-rs
    restart: always
    volumes:
      - ./app/src/static:/app/src/static



networks:
  default:
    external:
      name: ns2021-existing-network